apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: guardagent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: guardagent
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
