image:
  repository: ghcr.io/studiodeia/guardagent
  tag: "0.6.0"
service:
  port: 8080
resources:
  requests:
    cpu: 50m
    memory: 64Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
