// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/filter.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	mi := &file_api_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_api_filter_proto_rawDescGZIP(), []int{0}
}

func (x *FilterRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FilterRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type FilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterResponse) Reset() {
	*x = FilterResponse{}
	mi := &file_api_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterResponse) ProtoMessage() {}

func (x *FilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterResponse.ProtoReflect.Descriptor instead.
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return file_api_filter_proto_rawDescGZIP(), []int{1}
}

func (x *FilterResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *FilterResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_api_filter_proto protoreflect.FileDescriptor

const file_api_filter_proto_rawDesc = "" +
	"\n" +
	"\x10api/filter.proto\x12\x0eguardagent.api\"@\n" +
	"\rFilterRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"B\n" +
	"\x0eFilterResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action2X\n" +
	"\rFilterService\x12G\n" +
	"\x06Filter\x12\x1d.guardagent.api.FilterRequest\x1a\x1e.guardagent.api.FilterResponseB&Z$github.com/studiodeia/guardagent/apib\x06proto3"

var (
	file_api_filter_proto_rawDescOnce sync.Once
	file_api_filter_proto_rawDescData []byte
)

func file_api_filter_proto_rawDescGZIP() []byte {
	file_api_filter_proto_rawDescOnce.Do(func() {
		file_api_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_filter_proto_rawDesc), len(file_api_filter_proto_rawDesc)))
	})
	return file_api_filter_proto_rawDescData
}

var file_api_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_filter_proto_goTypes = []any{
	(*FilterRequest)(nil),  // 0: guardagent.api.FilterRequest
	(*FilterResponse)(nil), // 1: guardagent.api.FilterResponse
}
var file_api_filter_proto_depIdxs = []int32{
	0, // 0: guardagent.api.FilterService.Filter:input_type -> guardagent.api.FilterRequest
	1, // 1: guardagent.api.FilterService.Filter:output_type -> guardagent.api.FilterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_filter_proto_init() }
func file_api_filter_proto_init() {
	if File_api_filter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_filter_proto_rawDesc), len(file_api_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_filter_proto_goTypes,
		DependencyIndexes: file_api_filter_proto_depIdxs,
		MessageInfos:      file_api_filter_proto_msgTypes,
	}.Build()
	File_api_filter_proto = out.File
	file_api_filter_proto_goTypes = nil
	file_api_filter_proto_depIdxs = nil
}
