name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.8'
    - run: go vet ./...
    - run: gofmt -w $(git ls-files '*.go')
    - run: go test ./... -race
