name: Release
on:
  push:
    tags: ['v*']
permissions:
  id-token: write
  contents: write
jobs:
  release:
    uses: slsa-framework/slsa-github-generator/.github/workflows/reusable-go.yml@v1.8.0
    with:
      go-version: '1.22'
      config-file: .goreleaser.yaml
